title: My awesome title
author: alaprone
email: alaprone@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
  
  My other content.

# social links
twitter_username: my-twitter-handle
github_username:  my-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
